# Generated by Django 4.2.6 on 2024-04-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_courses_code_alter_instructor_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
