# Generated by Django 4.2.6 on 2024-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_instructor_sex_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=20, null=True),
        ),
    ]
